name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: |
          npm test

      - name: Build Docker Image
        run: |
          docker build -t akila-docker-image .

      - name: Push Docker Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push akila-docker-image

      - name: Deploy to AWS
        run: |
          scp -i dockerlab.ppk -r ./ ec2-user@54.224.198.168:/home/ec2-user/
          ssh -i dockerlab.ppk ec2-user@54.224.198.168 "docker pull akila-docker-image:latest && docker run -d -p 80:80 akila-docker-image:latest"
